# Generated by Django 3.0.2 on 2020-01-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagecontent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='homeSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('title', models.CharField(max_length=200)),
                ('sort_description', models.TextField(blank=True)),
            ],
        ),
    ]
