# Generated by Django 3.0.2 on 2020-01-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagecontent', '0003_categroypagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='categroypagecontent',
            name='page_image',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
