# Generated by Django 3.0.2 on 2020-01-18 08:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagecontent', '0004_categroypagecontent_page_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categroypagecontent',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
