# Generated by Django 3.0.2 on 2020-01-18 09:34

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagecontent', '0005_auto_20200118_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categroypagecontent',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
