# Generated by Django 3.0.2 on 2020-01-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagecontent', '0008_auto_20200118_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_name', models.CharField(blank=True, max_length=100)),
                ('icon_link', models.CharField(blank=True, max_length=100)),
                ('icon_code', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
