# Generated by Django 3.0.2 on 2020-01-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagecontent', '0009_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslider',
            name='description_color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='homeslider',
            name='title_color',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
